# Generated by Django 2.1.7 on 2019-02-28 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_center', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workcenter',
            name='production_type',
            field=models.CharField(choices=[('A', 'Assembly'), ('B', 'Electronics'), ('C', 'Machining'), ('D', 'Painting')], default='A', max_length=16),
        ),
    ]
