# Generated by Django 2.1.7 on 2019-02-26 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_component', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclecomponent',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
