# Generated by Django 2.1.7 on 2019-02-26 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_component', '0002_vehiclecomponent_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclecomponent',
            name='part_number',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
