# Generated by Django 2.1.7 on 2019-02-26 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_component', '0003_auto_20190226_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclecomponent',
            name='process_time',
            field=models.IntegerField(default=1),
        ),
    ]
