# Generated by Django 2.1.7 on 2019-02-28 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_component', '0004_vehiclecomponent_process_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclecomponent',
            name='facility_required',
            field=models.CharField(choices=[('A', 'Assembly'), ('B', 'Electronics'), ('C', 'Machining'), ('D', 'Painting')], default='A', max_length=16),
        ),
    ]
