# Generated by Django 2.1.7 on 2019-02-26 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicle_order', '0006_auto_20190226_2354'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=36)),
                ('on_schedule', models.BooleanField(default=True)),
                ('vehicle_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle_order.VehicleOrder')),
            ],
        ),
    ]
