# Generated by Django 2.1.7 on 2019-02-26 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=36)),
                ('order_code', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=64)),
                ('start_date', models.DateTimeField()),
                ('estimated_complete_date', models.DateTimeField()),
                ('bill_of_materials', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bom.Bom')),
            ],
        ),
    ]
