# Generated by Django 2.1.7 on 2019-02-26 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleorder',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
