# Generated by Django 2.1.7 on 2019-02-26 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_order', '0002_auto_20190226_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleorder',
            name='order_code',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
