# Generated by Django 2.1.7 on 2019-02-26 23:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_order', '0004_auto_20190226_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleorder',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 26, 23, 20, 49, 75040), editable=False),
        ),
        migrations.AlterField(
            model_name='vehicleorder',
            name='estimated_complete_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='vehicleorder',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 26, 23, 20, 49, 75083)),
        ),
    ]
