# Generated by Django 2.1.7 on 2019-02-26 23:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_order', '0005_auto_20190226_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleorder',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 26, 23, 54, 15, 618102), editable=False),
        ),
        migrations.AlterField(
            model_name='vehicleorder',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 26, 23, 54, 15, 618146)),
        ),
    ]
