# Generated by Django 2.1.7 on 2019-02-27 03:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_order', '0006_auto_20190226_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleorder',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='vehicleorder',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
